### ISSUE TITLE
Checklist to publish first pre-release

### ISSUE THREAD

**Issue by Serraniel** [Serraniel/AniwatchPlus#28]
Required
- [x] Checking compatibility and preparing Dev Accounts (Chrome, Firefox, Opera) (#21)
- [x] Finalizing manifest (#33)
- [x] Writing *readme.md*
- [x] Icon (#16)
- [x] Firefox validations (#38 and #39)
- [x] Permissions in *manifest.json* (#40)

Optional
- [x] Searching for beta users
- [ ] Some kind of menu with configuration options to disable specific features (#32)

**Comment by Serraniel** [comment]
Little update: I sent the first message in the Aniwatch Discord Donator´s channel for users who would like to test and send them the link to download.
Additionally I submitted the latest released beta version to following browsers who are now doing a review of the extension:
* Google Chrome
* Mozilla Firefox
* Opera

**Comment by Serraniel** [comment]
Firefox approved: https://addons.mozilla.org/de/firefox/addon/aniwatch-plus/

**Comment by Serraniel** [comment]
The extension now is in all major stores, so I will close this issue, too, as only optional checks are open, but beta release is now somehow completed and new versions will follow ;)

Chrome: https://chrome.google.com/webstore/detail/aniwatch-plus/hgniihpjiioldkafogebpkbaiflmpimb
Firefox: https://addons.mozilla.org/de/firefox/addon/aniwatch-plus/
Operra: https://addons.opera.com/de/extensions/details/aniwatch-plus/
